### ISSUE TITLE
Card hover effect

### ISSUE THREAD

**Issue by Shivampatel07** [Shivampatel07/Social_Media_Gallery_MERN_APP#1]
Could you please 🙏 implement card edits upon hover with a delete option? 🛠️💻👇 It would enhance user interaction and allow for quick removal of unwanted content. This feature will make our Social Media Gallery MERN App even more user-friendly and engaging. Your contribution in this direction is highly appreciated! How can we proceed with this enhancement? 🚀👷‍♂️🎉🔧💡📦

**Comment by homen19** [comment]
I am interested, you can assign it to me.

**Comment by Shivampatel07** [comment]
Ok, If you can just fork this and pull the request

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
